#+title: Datafest 2020 Files
* Free Gourds Datafest 2020 Project - Pomona College
Sam Millette

Guy Thampakkul: R code and statistical analysis

Tai Xiang: Python code and visualizations

* YouTube Video Transcript Sentiment Analysis Introduction:
With the rise of coronavirus infection rates and social impacts over the recent time period, we investigate whether individuals who upload 
YouTube videos have artificially/unconsciously created content that trends more towards relative positivity or negativity as infection rates
increase and time passes. Is there any relation between sentiment and government action towards virus? Is there any relation between social
perceptions of the virus and content sentiment? 

We take in the most popular YouTube videos uploaded by creators in Australia, Canada, India, the United Kingdom, and the United States on a two week cycle. We obtain the transcripts from the subtitles of these YouTube videos and perform sentiment analysis on them.

These videos are also filtered by category. Do content creators who upload entertainment related videos create videos that display a more positive sentiment over time compared to those who upload educational videos? What about those that upload videos related to music and those that upload videos related to politics and government? Does this at all correlate to country policy or culture?

* Python Code
** youtube_scraping folder:
Details how YouTube video dataset was obtained and how the transcripts for each YouTube video were extracted. Also includes how transcript dataset was cleaned and pre-processed.

** LSTM_training folder:
Details how the LSTM deep learning model used in this project was built, optimized and deployed. Also includes how training data was pre-processed and how the YouTube data-set was pre-processed in order to be compatible with the deep learning model.

* R Code and Generated Files
** R_Analysis Folder
Contains all R code used in analysis of dataset. Tests include linear regression, two-proportion Z test, two-independent-mean T test. PDF files include the outputted graphs and results yielded by the code. 
